### ISSUE TITLE
Cannot receive compressed image from unity

### ISSUE THREAD

**Issue by qiancaoyiyouyou** [siemens/ros-sharp#212] opened 2019-06-11 13:14 UTC
I am a novice at  ROS# and ROS. I just want to use ROS to receive RGB camera image in unity .I have received compressed image through ROS node and successfully used OpenCV for display.

 However ,when I wanted to use the same method to obtain compressed image information and run ORB_SLAM2 though ROS,I could not receive the image.
I tried all  the possible solutions I could find,but they were unsuccessful.Can you give me some advice? Thank you very much!

**Comment by berkayalpcakal** [comment] 2019-06-12 11:22
Hello,

For me to understand whether the issue is related to ROS# or not, could you please write down the steps to reproduce the issue? I suggest that you close this issue and open a new one by using the issue template.

Thanks.

**Closed** 2019-06-12 11:37 UTC
